###################  项目启动端口  ###################
server:
  port: 8080

###################  spring配置  ###################
spring:
  profiles:
    active: dev
  ##########################################################
  ###################  开发环境的profile  ###################
  ##########################################################
  datasource:
    ## serverTimezone=UTC&nullCatalogMeansCurrent=true 解决启动报错问题
    url: jdbc:mysql://127.0.0.1:3307/flowable_test?serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 123456

logging:
  level.root: info
  level.com.haiyang: debug
  path: logs/
  file: flowable-test.log


---
logging:
  level.root: warn
  path: logs/
  file: flowable-test.log